### ISSUE TITLE
Depending on Wifi or 3G connection, start method needs LongPollingTransport instance

### ISSUE THREAD

**Issue by ghost** [SignalR/java-client#43] opened 2014-11-17 09:18 UTC
Hello,

I have an issue with SignalR java-client. it is simply, if my device has a WIFI connection I have to start connection with parameterless start method, otherwise I have to send a LongPollingTransport instance to start method. if I do not do this after a while SignalR disconnects thus it stops working properly.

In this case, I am making user to select what kind of connection his device has, but I really dont want my user to make this choice.

Could you please help me on this? thank you. I appreciate your help.

simply  my code is 

```
             lpt = new LongPollingTransport(new Logger() 
    {       
        @Override
        public void log(String message, LogLevel level) 
        {

        }
    });

    SignalRFuture<Void> awaitConnection = null;

    if(!wifi)
     awaitConnection = con.start(lpt);
    else
     awaitConnection = con.start();
    try
    {
        awaitConnection.get();
        connected=true;
        firstStart=false;
    } 
    catch (InterruptedException e)
    {
        ConnectExceptionRecieved();
    } 
```

**Comment by gouravd** [comment] 2015-01-20 20:48
In my case, irrespective of the connection type, the connection never completes when transport is Automatic/Websocket.

I am wondering if it has something to do with the Websocket jar itself

**Comment by arnoldpistorius** [comment] 2015-01-22 06:45
I can confirm that Websocket is working, but your server SignalR version needs to support it. You should check what version of SignalR you are running.

**Comment by gouravd** [comment] 2015-01-22 07:03
For me, its the latest version of SignalR now. Websockets is working via Javascript (our website), but I can't seem to get it working on the mobile.

**Comment by anzaidemirzoi** [comment] 2015-01-23 10:08
I updated my signalR version to latest but I faced another problem. I opened another issue so if it gets a soulution this will do, too and I will close this issue. @arnoldpistorius my server version is 2.2 client version is the current latest.

**Comment by aspnet-hello** [comment] 2018-09-20 18:20
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.

**Closed as completed by aspnet-hello** 2018-09-20 18:20 UTC
